version: '3.9'

services:
  app:
    container_name: menu_microservice
    build: .
    ports:
      - "5001:5001"
    depends_on:
      - menu_postgres_db
    env_file:
      - .env.stage.docker

  menu_postgres_db:
    image: postgres:latest
    restart: always
    ports:
      - "9901:5432"
    env_file:
      - .env.stage.docker
    volumes:
      - pg_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8801:8080

volumes:
  pg_data:
