services:
  menu-app:
    container_name: menu_microservice
    build:
      context: .
      target: dev
    ports:
      - "5001:5001"
    depends_on:
      - menu-postgres-db
    env_file:
      - .env.stage.docker

  menu-postgres-db:
    container_name: postgres-menu_db
    image: postgres:latest
    ports:
      - "9901:5432"
    env_file:
      - .env.stage.docker
    volumes:
      - pg_data:/var/lib/postgresql/data

  adminer:
    container_name: adminer-menu_db
    image: adminer
    ports:
      - 8801:8080

volumes:
  pg_data:
